name: Compilar APK Android

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.47.1'
          channel: stable
          cache: true

      - name: Crear plataforma Android
        run: bash tool/bootstrap_android.sh

      - name: Analizar proyecto
        run: flutter analyze

      - name: Compilar APK
        run: flutter build apk --release

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: lector-academico-android
          path: build/app/outputs/flutter-apk/app-release.apk
